# Generated by Django 5.1.2 on 2024-11-20 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Point de prediction eolien', 'Eolien'), ('Point de prediction solair', 'Solair')], max_length=30, verbose_name='Type de production')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date pour laquelle cette prediction est faite.')),
                ('valeur', models.FloatField(default=None, null=True, verbose_name='Valeur de la prediction.')),
            ],
        ),
        migrations.CreateModel(
            name='TempoClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date pour laquelle cette classification est faite.')),
                ('by_RTE', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('WHITE', 'White')], max_length=5, verbose_name='Classification par RTE')),
                ('ours_J_1', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('WHITE', 'White')], max_length=5, verbose_name='Notre classification J-1')),
                ('ours_J_2', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('WHITE', 'White')], max_length=5, verbose_name='Notre classification J-2')),
                ('ours_J_3', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('WHITE', 'White')], max_length=5, verbose_name='Notre classification J-3')),
            ],
        ),
    ]
